[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "raven pepper smooth myself estate crowd cousin great saddle pigeon slow fall angry shadow fix brass thumb share arrow either decline open capital mixture"
